# Generated by Django 4.2.5 on 2023-10-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
