# Generated by Django 4.2.5 on 2023-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_reset_token_user_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='reset_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
