# Generated by Django 4.2.5 on 2023-10-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_historicaluser_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
