# Generated by Django 4.2.5 on 2023-09-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_historicalsaledetail_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsale',
            old_name='employe',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='employe',
            new_name='employee',
        ),
    ]
