# Generated by Django 4.2.5 on 2023-09-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job_promotion',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='historicalemployee',
            name='job_promotion',
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Wife', 'wife'), ('Husband', 'husband'), ('Sister', 'sister'), ('Son', 'son'), ('Mother', 'motherr'), ('Father', 'father'), ('Brother', 'brother')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Wife', 'wife'), ('Husband', 'husband'), ('Sister', 'sister'), ('Son', 'son'), ('Mother', 'motherr'), ('Father', 'father'), ('Brother', 'brother')], max_length=10),
        ),
    ]
