# Generated by Django 4.2.5 on 2023-09-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_company_remove_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Son', 'son'), ('Mother', 'motherr'), ('Wife', 'wife'), ('Sister', 'sister'), ('Brother', 'brother'), ('Daughter', 'daughter'), ('Husband', 'husband')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Son', 'son'), ('Mother', 'motherr'), ('Wife', 'wife'), ('Sister', 'sister'), ('Brother', 'brother'), ('Daughter', 'daughter'), ('Husband', 'husband')], max_length=10),
        ),
    ]
