# Generated by Django 4.2.5 on 2023-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_historicalemployee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Father', 'father'), ('Mother', 'motherr'), ('Brother', 'brother'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband'), ('Wife', 'wife')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Father', 'father'), ('Mother', 'motherr'), ('Brother', 'brother'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband'), ('Wife', 'wife')], max_length=10),
        ),
    ]
