# Generated by Django 4.2.5 on 2023-09-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Daughter', 'daughter'), ('Mother', 'motherr'), ('Father', 'father'), ('Wife', 'wife'), ('Sister', 'sister'), ('Son', 'son'), ('Brother', 'brother')], max_length=10),
        ),
    ]
