# Generated by Django 4.2.5 on 2023-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Mother', 'motherr'), ('Brother', 'brother'), ('Daughter', 'daughter'), ('Son', 'son'), ('Wife', 'wife'), ('Father', 'father'), ('Husband', 'husband'), ('Sister', 'sister')], max_length=10),
        ),
    ]
