# Generated by Django 4.2.5 on 2023-09-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Brother', 'brother'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Son', 'son'), ('Husband', 'husband'), ('Father', 'father'), ('Wife', 'wife')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Brother', 'brother'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Son', 'son'), ('Husband', 'husband'), ('Father', 'father'), ('Wife', 'wife')], max_length=10),
        ),
    ]
