# Generated by Django 4.2.5 on 2023-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Wife', 'wife'), ('Brother', 'brother'), ('Son', 'son'), ('Mother', 'motherr'), ('Sister', 'sister'), ('Father', 'father'), ('Daughter', 'daughter')], max_length=10),
        ),
    ]
