# Generated by Django 4.2.5 on 2023-09-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_remove_jobposition_employee'),
        ('employees', '0004_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.jobposition'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='job_position',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.jobposition'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Mother', 'motherr'), ('Sister', 'sister'), ('Brother', 'brother'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son'), ('Wife', 'wife'), ('Father', 'father')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Mother', 'motherr'), ('Sister', 'sister'), ('Brother', 'brother'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son'), ('Wife', 'wife'), ('Father', 'father')], max_length=10),
        ),
    ]
