# Generated by Django 4.2.5 on 2023-09-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_gender_alter_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Daughter', 'daughter'), ('Father', 'father'), ('Son', 'son'), ('Wife', 'wife'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Daughter', 'daughter'), ('Father', 'father'), ('Son', 'son'), ('Wife', 'wife'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
    ]
