# Generated by Django 4.2.5 on 2023-09-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_job_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son'), ('Sister', 'sister'), ('Father', 'father'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son'), ('Sister', 'sister'), ('Father', 'father'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
    ]
