# Generated by Django 4.2.5 on 2023-09-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Sister', 'sister'), ('Wife', 'wife'), ('Brother', 'brother'), ('Son', 'son'), ('Mother', 'motherr'), ('Daughter', 'daughter'), ('Husband', 'husband')], max_length=10),
        ),
    ]
