# Generated by Django 4.2.5 on 2023-09-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband'), ('Mother', 'motherr'), ('Father', 'father'), ('Brother', 'brother'), ('Daughter', 'daughter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband'), ('Mother', 'motherr'), ('Father', 'father'), ('Brother', 'brother'), ('Daughter', 'daughter')], max_length=10),
        ),
    ]
