# Generated by Django 4.2.5 on 2023-09-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Mother', 'motherr'), ('Daughter', 'daughter'), ('Wife', 'wife'), ('Husband', 'husband'), ('Sister', 'sister'), ('Brother', 'brother'), ('Father', 'father'), ('Son', 'son')], max_length=10),
        ),
    ]
