# Generated by Django 4.2.5 on 2023-09-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Daughter', 'daughter'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Husband', 'husband'), ('Brother', 'brother'), ('Wife', 'wife'), ('Son', 'son')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Daughter', 'daughter'), ('Sister', 'sister'), ('Mother', 'motherr'), ('Husband', 'husband'), ('Brother', 'brother'), ('Wife', 'wife'), ('Son', 'son')], max_length=10),
        ),
    ]
