# Generated by Django 4.2.5 on 2023-09-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Brother', 'brother'), ('Husband', 'husband'), ('Sister', 'sister'), ('Wife', 'wife'), ('Daughter', 'daughter'), ('Mother', 'motherr'), ('Father', 'father'), ('Son', 'son')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Brother', 'brother'), ('Husband', 'husband'), ('Sister', 'sister'), ('Wife', 'wife'), ('Daughter', 'daughter'), ('Mother', 'motherr'), ('Father', 'father'), ('Son', 'son')], max_length=10),
        ),
    ]
