# Generated by Django 4.2.5 on 2023-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Brother', 'brother'), ('Son', 'son'), ('Mother', 'motherr'), ('Father', 'father'), ('Daughter', 'daughter'), ('Husband', 'husband'), ('Sister', 'sister')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Wife', 'wife'), ('Brother', 'brother'), ('Son', 'son'), ('Mother', 'motherr'), ('Father', 'father'), ('Daughter', 'daughter'), ('Husband', 'husband'), ('Sister', 'sister')], max_length=10),
        ),
    ]
