# Generated by Django 4.2.5 on 2023-09-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Wife', 'wife'), ('Father', 'father'), ('Brother', 'brother'), ('Mother', 'motherr'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Wife', 'wife'), ('Father', 'father'), ('Brother', 'brother'), ('Mother', 'motherr'), ('Husband', 'husband'), ('Daughter', 'daughter'), ('Son', 'son')], max_length=10),
        ),
    ]
