# Generated by Django 4.2.5 on 2023-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Daughter', 'daughter'), ('Wife', 'wife'), ('Mother', 'motherr'), ('Father', 'father'), ('Sister', 'sister'), ('Brother', 'brother'), ('Son', 'son')], max_length=10),
        ),
    ]
