# Generated by Django 4.2.5 on 2023-09-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Brother', 'brother'), ('Mother', 'motherr'), ('Wife', 'wife'), ('Father', 'father'), ('Daughter', 'daughter'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Brother', 'brother'), ('Mother', 'motherr'), ('Wife', 'wife'), ('Father', 'father'), ('Daughter', 'daughter'), ('Sister', 'sister'), ('Son', 'son'), ('Husband', 'husband')], max_length=10),
        ),
    ]
