# Generated by Django 4.2.5 on 2023-10-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Brother', 'brother'), ('Wife', 'wife'), ('Son', 'son'), ('Husband', 'husband'), ('Sister', 'sister'), ('Father', 'father'), ('Daughter', 'daughter'), ('Mother', 'motherr')], max_length=10),
        ),
    ]
