# Generated by Django 4.2.5 on 2023-10-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Daughter', 'daughter'), ('Sister', 'sister'), ('Wife', 'wife'), ('Father', 'father'), ('Husband', 'husband'), ('Mother', 'motherr'), ('Brother', 'brother'), ('Son', 'son')], max_length=10),
        ),
    ]
