# Generated by Django 4.2.5 on 2023-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Father', 'father'), ('Daughter', 'daughter'), ('Husband', 'husband'), ('Son', 'son'), ('Wife', 'wife'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Father', 'father'), ('Daughter', 'daughter'), ('Husband', 'husband'), ('Son', 'son'), ('Wife', 'wife'), ('Mother', 'motherr'), ('Brother', 'brother')], max_length=10),
        ),
    ]
