# Generated by Django 4.2.5 on 2023-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_alter_familymember_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Husband', 'husband'), ('Mother', 'motherr'), ('Brother', 'brother'), ('Daughter', 'daughter'), ('Father', 'father'), ('Son', 'son'), ('Wife', 'wife'), ('Sister', 'sister')], max_length=10),
        ),
    ]
