# Generated by Django 4.2.5 on 2023-10-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Son', 'son'), ('Wife', 'wife'), ('Mother', 'motherr'), ('Husband', 'husband'), ('Sister', 'sister'), ('Brother', 'brother'), ('Daughter', 'daughter'), ('Father', 'father')], max_length=10),
        ),
    ]
