# Generated by Django 4.2.5 on 2023-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Father', 'father'), ('Husband', 'husband'), ('Son', 'son'), ('Daughter', 'daughter'), ('Brother', 'brother'), ('Mother', 'motherr'), ('Wife', 'wife')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfamilymember',
            name='relation',
            field=models.CharField(choices=[('Sister', 'sister'), ('Father', 'father'), ('Husband', 'husband'), ('Son', 'son'), ('Daughter', 'daughter'), ('Brother', 'brother'), ('Mother', 'motherr'), ('Wife', 'wife')], max_length=10),
        ),
    ]
