# Generated by Django 4.2.5 on 2023-10-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Father', 'father'), ('Sister', 'sister'), ('Husband', 'husband'), ('Son', 'son'), ('Wife', 'wife'), ('Mother', 'motherr'), ('Brother', 'brother'), ('Daughter', 'daughter')], max_length=10),
        ),
    ]
