# Generated by Django 4.2.5 on 2023-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_gender_alter_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Son', 'son'), ('Father', 'father'), ('Brother', 'brother'), ('Mother', 'motherr'), ('Sister', 'sister'), ('Daughter', 'daughter'), ('Husband', 'husband'), ('Wife', 'wife')], max_length=10),
        ),
    ]
