# Generated by Django 4.2.5 on 2023-09-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'JobPosition',
                'verbose_name_plural': 'JobPositions',
            },
        ),
        migrations.CreateModel(
            name='JobPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now=True, null=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('employee', models.PositiveIntegerField()),
                ('old_job_position', models.IntegerField()),
                ('old_department', models.IntegerField()),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_job_position', models.IntegerField()),
                ('new_department', models.IntegerField()),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_start_new_position', models.DateField()),
            ],
            options={
                'verbose_name': 'JobPromotion',
                'verbose_name_plural': 'JobPromotions',
            },
        ),
    ]
