# Generated by Django 4.2.5 on 2023-09-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_company_remove_employee_department_and_more'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobpromotion',
            name='employee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobposition',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='jobpromotion',
            name='employee',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
