# Generated by Django 4.2.5 on 2023-09-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_gender_alter_familymember_gender_and_more'),
        ('positions', '0002_historicaljobpromotion_employee_jobposition_employe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='employe',
        ),
        migrations.AddField(
            model_name='jobposition',
            name='employee',
            field=models.ManyToManyField(to='employees.employee'),
        ),
    ]
