# Generated by Django 4.2.5 on 2023-09-20 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_remove_jobposition_employe_jobposition_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='employee',
        ),
    ]
