# Generated by Django 4.2.5 on 2023-09-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('document', models.FileField(upload_to='employess/docs/')),
                ('type', models.CharField(choices=[('Diplomas', 7), ('Antecedentes Policiacos', 3), ('Curriculum', 2), ('Certificaciones', 6), ('Titulos', 5), ('Antecedentes Penales', 4), ('Identification', 1)], max_length=50)),
                ('expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'EmployeDocuments',
                'verbose_name_plural': 'EmployeDocumentss',
            },
        ),
    ]
