# Generated by Django 4.2.5 on 2023-09-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Penales', 4), ('Diplomas', 7), ('Titulos', 5), ('Curriculum', 2), ('Identification', 1), ('Antecedentes Policiacos', 3), ('Certificaciones', 6)], max_length=50),
        ),
    ]
