# Generated by Django 4.2.5 on 2023-09-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Titulos', 5), ('Certificaciones', 6), ('Diplomas', 7), ('Antecedentes Penales', 4), ('Curriculum', 2), ('Identification', 1)], max_length=50),
        ),
    ]
