# Generated by Django 4.2.5 on 2023-09-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Curriculum', 2), ('Antecedentes Policiacos', 3), ('Diplomas', 7), ('Antecedentes Penales', 4), ('Identification', 1), ('Certificaciones', 6), ('Titulos', 5)], max_length=50),
        ),
    ]
