# Generated by Django 4.2.5 on 2023-09-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Identification', 1), ('Curriculum', 2), ('Antecedentes Policiacos', 3), ('Antecedentes Penales', 4), ('Diplomas', 7), ('Titulos', 5), ('Certificaciones', 6)], max_length=50),
        ),
    ]
