# Generated by Django 4.2.5 on 2023-09-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Diplomas', 7), ('Identification', 1), ('Certificaciones', 6), ('Antecedentes Penales', 4), ('Curriculum', 2), ('Titulos', 5)], max_length=50),
        ),
    ]
