<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-20 22:21
=======
# Generated by Django 4.2.5 on 2023-09-20 01:03
>>>>>>> origin/frontend

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
<<<<<<< HEAD
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Identification', 1), ('Curriculum', 2), ('Diplomas', 7), ('Antecedentes Penales', 4), ('Certificaciones', 6), ('Titulos', 5)], max_length=50),
=======
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Curriculum', 2), ('Antecedentes Penales', 4), ('Certificaciones', 6), ('Diplomas', 7), ('Titulos', 5), ('Identification', 1)], max_length=50),
>>>>>>> origin/frontend
        ),
    ]
