<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-09-21 02:21
=======
# Generated by Django 4.2.5 on 2023-09-20 20:12
>>>>>>> origin/frontend

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
<<<<<<< HEAD
            field=models.CharField(choices=[('Certificaciones', 6), ('Diplomas', 7), ('Titulos', 5), ('Antecedentes Penales', 4), ('Curriculum', 2), ('Antecedentes Policiacos', 3), ('Identification', 1)], max_length=50),
=======
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Diplomas', 7), ('Certificaciones', 6), ('Identification', 1), ('Curriculum', 2), ('Antecedentes Penales', 4), ('Titulos', 5)], max_length=50),
>>>>>>> origin/frontend
        ),
    ]
