# Generated by Django 4.2.5 on 2023-09-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Certificaciones', 6), ('Identification', 1), ('Titulos', 5), ('Antecedentes Policiacos', 3), ('Curriculum', 2), ('Antecedentes Penales', 4), ('Diplomas', 7)], max_length=50),
        ),
    ]
