# Generated by Django 4.2.5 on 2023-09-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Certificaciones', 6), ('Diplomas', 7), ('Antecedentes Policiacos', 3), ('Curriculum', 2), ('Antecedentes Penales', 4), ('Identification', 1), ('Titulos', 5)], max_length=50),
        ),
    ]
