# Generated by Django 4.2.5 on 2023-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Penales', 4), ('Diplomas', 7), ('Antecedentes Policiacos', 3), ('Certificaciones', 6), ('Titulos', 5), ('Curriculum', 2), ('Identification', 1)], max_length=50),
        ),
    ]
