# Generated by Django 4.2.5 on 2023-09-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0015_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Titulos', 5), ('Antecedentes Penales', 4), ('Antecedentes Policiacos', 3), ('Certificaciones', 6), ('Identification', 1), ('Curriculum', 2), ('Diplomas', 7)], max_length=50),
        ),
    ]
