# Generated by Django 4.2.5 on 2023-10-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0016_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Diplomas', 7), ('Identification', 1), ('Curriculum', 2), ('Certificaciones', 6), ('Titulos', 5), ('Antecedentes Penales', 4)], max_length=50),
        ),
    ]
