# Generated by Django 4.2.5 on 2023-09-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Diplomas', 7), ('Antecedentes Policiacos', 3), ('Titulos', 5), ('Antecedentes Penales', 4), ('Certificaciones', 6), ('Curriculum', 2), ('Identification', 1)], max_length=50),
        ),
    ]
