# Generated by Django 4.2.5 on 2023-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0021_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Diplomas', 7), ('Curriculum', 2), ('Titulos', 5), ('Certificaciones', 6), ('Antecedentes Policiacos', 3), ('Antecedentes Penales', 4), ('Identification', 1)], max_length=50),
        ),
    ]
