# Generated by Django 4.2.5 on 2023-10-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0033_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Penales', 4), ('Curriculum', 2), ('Certificaciones', 6), ('Diplomas', 7), ('Identification', 1), ('Antecedentes Policiacos', 3), ('Titulos', 5)], max_length=50),
        ),
    ]
