# Generated by Django 4.2.5 on 2023-10-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0042_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Policiacos', 3), ('Titulos', 5), ('Identification', 1), ('Antecedentes Penales', 4), ('Certificaciones', 6), ('Diplomas', 7), ('Curriculum', 2)], max_length=50),
        ),
    ]
