# Generated by Django 4.2.5 on 2023-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0043_alter_employedocuments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employedocuments',
            name='type',
            field=models.CharField(choices=[('Antecedentes Penales', 4), ('Identification', 1), ('Antecedentes Policiacos', 3), ('Titulos', 5), ('Curriculum', 2), ('Diplomas', 7), ('Certificaciones', 6)], max_length=50),
        ),
    ]
