# Generated by Django 4.2.5 on 2023-09-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_alter_familymember_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Pay',
                'verbose_name_plural': 'Pays',
            },
        ),
    ]
