# Generated by Django 4.2.5 on 2023-09-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0002_prepaid_month_prepaid_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaid',
            name='day',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
