# Generated by Django 4.2.5 on 2023-09-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_gender_alter_familymember_gender_and_more'),
        ('pays', '0003_prepaid_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='prepaid',
            unique_together={('employee', 'year', 'month')},
        ),
    ]
