# Generated by Django 4.2.5 on 2023-09-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0005_alter_prepaid_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaid',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
