# Generated by Django 4.2.5 on 2023-09-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0007_prepaid_created_prepaid_created_by_prepaid_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprepaid',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Prepaid', 'verbose_name_plural': 'historical Prepaids'},
        ),
        migrations.AlterModelOptions(
            name='prepaid',
            options={'verbose_name': 'Prepaid', 'verbose_name_plural': 'Prepaids'},
        ),
    ]
