# Generated by Django 4.2.5 on 2023-09-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0010_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('2', 'Mes'), ('4', 'Aguinaldo'), ('3', 'Bono 14'), ('1', 'Quincena')], default=1, max_length=15),
        ),
    ]
