# Generated by Django 4.2.5 on 2023-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0015_alter_payment_type_monthlypayment_fortnightpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1', 'Quincena'), ('2', 'Mes'), ('4', 'Aguinaldo'), ('3', 'Bono 14')], default=1, max_length=15),
        ),
    ]
