# Generated by Django 4.2.5 on 2023-10-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0016_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortnightpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fortnightpayment',
            name='credit_store',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fortnightpayment',
            name='month',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='fortnightpayment',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fortnightpayment',
            name='year',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='credit_store',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='month',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='year',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1', 'Quincena'), ('4', 'Aguinaldo'), ('2', 'Mes'), ('3', 'Bono 14')], default=1, max_length=15),
        ),
    ]
