# Generated by Django 4.2.5 on 2023-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0017_alter_fortnightpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('3', 'Bono 14'), ('1', 'Quincena'), ('2', 'Mes'), ('4', 'Aguinaldo')], default=1, max_length=15),
        ),
    ]
