# Generated by Django 4.2.5 on 2023-10-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0022_alter_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1', 'Quincena'), ('3', 'Bono 14'), ('2', 'Mes'), ('4', 'Aguinaldo')], default=1, max_length=15),
        ),
    ]
