# Generated by Django 4.2.5 on 2023-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0026_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnightpayment',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('2', 'Mes'), ('1', 'Quincena'), ('4', 'Aguinaldo'), ('3', 'Bono 14')], default=1, max_length=15),
        ),
    ]
