# Generated by Django 4.2.5 on 2023-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0024_alter_employee_gender_alter_familymember_gender'),
        ('pays', '0027_fortnightpayment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('1', 'Quincena'), ('2', 'Mes'), ('4', 'Aguinaldo'), ('3', 'Bono 14')], default=1, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayment',
            unique_together={('employee', 'year', 'month')},
        ),
    ]
