# Generated by Django 4.2.5 on 2023-10-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0028_alter_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('4', 'Aguinaldo'), ('1', 'Quincena'), ('3', 'Bono 14'), ('2', 'Mes')], default=1, max_length=15),
        ),
    ]
