# Generated by Django 4.2.5 on 2023-10-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0037_alter_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortnightpayment',
            name='bono3701',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='bono3701',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('2', 'Mes'), ('1', 'Quincena'), ('3', 'Bono 14'), ('4', 'Aguinaldo')], default=1, max_length=15),
        ),
    ]
