# Generated by Django 4.2.5 on 2023-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0038_fortnightpayment_bono3701_monthlypayment_bono3701_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('4', 'Aguinaldo'), ('1', 'Quincena'), ('2', 'Mes'), ('3', 'Bono 14')], default=1, max_length=15),
        ),
    ]
