# Generated by Django 4.2.5 on 2023-10-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0042_aguinaldopayment_bonopayment_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aguinaldopayment',
            options={'ordering': ['year', 'month'], 'verbose_name': 'AguinaldoPayment', 'verbose_name_plural': 'AguinaldoPayments'},
        ),
        migrations.AlterModelOptions(
            name='bonopayment',
            options={'ordering': ['year', 'month'], 'verbose_name': 'BonoPayment', 'verbose_name_plural': 'BonoPayments'},
        ),
        migrations.AlterField(
            model_name='aguinaldopayment',
            name='type_payment',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='bonopayment',
            name='type_payment',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
